[package]
name = "starb"
description = "STAtic Ring Buffers."
version = "0.3.0"
authors = ["Brian Cully <bjc@kublai.com>"]
edition = "2018"
license = "LGPL-3.0-or-later"
repository = "https://github.com/bjc/starb.git"
readme = "README.md"
